upgrade function [skip ci]

diff --git a/bin/kn b/bin/kn
--- a/bin/kn
+++ b/bin/kn
@@ -29,26 +29,20 @@ Commands:
 TEXT_END
 }
 
-# Validate command
-if [ "$#" -eq 0 ]; then
-  >&2 echo "Error: no arguments supplied"
-  usage
-  exit 1
-fi
-
-COMMAND="$1"
-ALLOWED="help init terraform ansible ansible-playbook kubetoken apply destroy kubectl helm openstack az ssh bash"
-if ! grep -qw "$COMMAND" <<< "$ALLOWED"; then
-  >&2 echo "Error: unrecognized command '$COMMAND'"
-  usage
-  exit 1
-fi
-
-# Print help if required
-if [ "$COMMAND" = "help" ]; then
-  usage
-  exit 0
-fi
+# Inspired by https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
+function resolve_links
+{
+  source=$1
+  # resolve $source until the file is no longer a symlink
+  while [ -h "$source" ]; do
+    dir="$( cd -P "$( dirname "$source" )" && pwd )"
+    # if $dir was a relative symlink, we need to resolve it relative to
+    # the path where the symlink file was located
+    source="$(readlink "$source")"
+    [[ $dir != /* ]] && dir="$dir/$dir"
+  done
+  echo "$source"
+}
 
 # If no version specified take stable
 if [ -z "$KUBENOW_VERSION" ] ; then
@@ -63,69 +57,114 @@ first="$1"; shift; set -- "${first/init/init-kn}" "$@"
 # Get all local user group id:s (to be added to user inside docker-image)
 LOCAL_GROUP_IDS="$(id -G)"
 
-if [ "$COMMAND" = "init" ]; then
+case "$1" in
+    help)
+        usage
+        exit
+        ;;
 
-  # Validate
-  if [ "$#" -ne 3 ]; then
-    >&2 echo "Error: wrong number of argument for the init command"
-    usage
-    exit 1
-  fi
+    upgrade)
+        latest="$(curl https://api.github.com/repos/kubenow/KubeNow/releases | \
+                  jq -r '.[0].tag_name')"
+        latest_stable="$(curl https://api.github.com/repos/kubenow/KubeNow/releases | \
+                         jq -r '[.[] | select(.prerelease==false) | .tag_name'][0])"
+        master=
+        laterst_url=
+        latest_stabe_url=
+        master_url=
 
-  HOST_CLOUD="$2"
-  # Check for recognized cloud provider
-  if ! grep -qw "$HOST_CLOUD" <<< "openstack gce azure aws"; then
-    >&2 echo "Error: unrecognized host cloud '$HOST_CLOUD'"
-    exit 1
-  fi
+        # get full filename of this script
+        absolute_file="$(resolve_links ${BASH_SOURCE[0]})"
+        echo "absolute_file=$absolute_file"
 
-  # shellcheck disable=SC2086,SC2046
-  INIT_DIR=$(cd $(dirname $3) && echo $PWD/$(basename $3))
-  if [ -f "$INIT_DIR" ] || [ -d "$INIT_DIR" ]; then
-    >&2 echo "Error: $INIT_DIR already exists"
-    exit 1
-  fi
+        # download new version to temp
 
-  mkdir -p "$INIT_DIR"
+        # copy file over old
 
-  # Wrap docker run
-  # shellcheck disable=SC2086
-  docker run --rm -it \
-    -v "$INIT_DIR":/KubeNow_config/ \
-    -v "$INIT_DIR":/KubeNow_root/ \
-    -e "LOCAL_USER_ID=$UID" \
-    -e "LOCAL_GROUP_IDS=$LOCAL_GROUP_IDS" \
-    kubenow/provisioners:"$KUBENOW_VERSION" \
-    "/opt/KubeNow/bin/docker-entrypoint" "$@"
-else
+        # rm temp
 
-  # Validate PWD (not needed for a selection of commands)
-  if ! grep -qw "$COMMAND" <<< "kubetoken az bash"; then
-    if [ ! -f ssh_key ] || [ ! -f ssh_key.pub ] ; then
-        >&2 echo "Error: ssh_key not found. Are you in the right directory?"
+        # pull latest docker
+        docker pull
+
+        exit
+        ;;
+
+    init)
+        # Validate
+        if [ "$#" -ne 3 ]; then
+          >&2 echo "Error: wrong number of argument for the init command"
+          usage
+          exit 1
+        fi
+
+        HOST_CLOUD="$2"
+        # Check for recognized cloud provider
+        if ! grep -qw "$HOST_CLOUD" <<< "openstack gce azure aws"; then
+          >&2 echo "Error: unrecognized host cloud '$HOST_CLOUD'"
+          exit 1
+        fi
+
+        # shellcheck disable=SC2086,SC2046
+        INIT_DIR=$(cd $(dirname $3) && echo $PWD/$(basename $3))
+        if [ -f "$INIT_DIR" ] || [ -d "$INIT_DIR" ]; then
+          >&2 echo "Error: $INIT_DIR already exists"
+          exit 1
+        fi
+
+        mkdir -p "$INIT_DIR"
+
+        # Wrap docker run
+        # shellcheck disable=SC2086
+        docker run --rm -it \
+          -v "$INIT_DIR":/KubeNow_config/ \
+          -v "$INIT_DIR":/KubeNow_root/ \
+          -e "LOCAL_USER_ID=$UID" \
+          -e "LOCAL_GROUP_IDS=$LOCAL_GROUP_IDS" \
+          kubenow/provisioners:"$KUBENOW_VERSION" \
+          "/opt/KubeNow/bin/docker-entrypoint" "$@"
+        ;;
+
+    terraform|ansible|ansible-playbook|kubetoken|apply|destroy|kubectl|helm|openstack|az|ssh|bash)
+        # Validate PWD (not needed for a selection of commands)
+        if ! grep -qw "$COMMAND" <<< "kubetoken az bash"; then
+          if [ ! -f ssh_key ] || [ ! -f ssh_key.pub ] ; then
+              >&2 echo "Error: ssh_key not found. Are you in the right directory?"
+              exit 1
+          fi
+          if [ ! -f terraform.tfvars ] ; then
+              >&2 echo "Error: terraform.tfvars not found. Please create one using the templates."
+              exit 1
+          fi
+        fi
+
+        # Wrap docker run
+        # shellcheck disable=SC2086
+        docker run --rm -it \
+          -v "$PWD":/KubeNow_config/ \
+          -v "$PWD":/KubeNow_root/ \
+          -e "LOCAL_USER_ID=$UID" \
+          -e "LOCAL_GROUP_IDS=$LOCAL_GROUP_IDS" \
+          -e "TERRAFORM_OPT=$TERRAFORM_OPT" \
+          -e "ANSIBLE_OPT=$ANSIBLE_OPT" \
+          --env-file <(env | grep OS_) \
+          --env-file <(env | grep TF_) \
+          --env-file <(env | grep GOOGLE_) \
+          --env-file <(env | grep AWS_) \
+          --env-file <(env | grep ARM_) \
+          --env-file <(env | grep KUBENOW_) \
+          kubenow/provisioners:"$KUBENOW_VERSION" \
+          "/KubeNow_root/bin/docker-entrypoint" "$@"
+        ;;
+    "")
+        echo "No <command> specified" >&2
+        usage
+        exit
+        ;;
+    *)
+        printf '"%s" is not a valid command\n' "$1" >&2
+        usage
         exit 1
-    fi
-    if [ ! -f terraform.tfvars ] ; then
-        >&2 echo "Error: terraform.tfvars not found. Please create one using the templates."
-        exit 1
-    fi
-  fi
+        ;;
 
-  # Wrap docker run
-  # shellcheck disable=SC2086
-  docker run --rm -it \
-    -v "$PWD":/KubeNow_config/ \
-    -v "$PWD":/KubeNow_root/ \
-    -e "LOCAL_USER_ID=$UID" \
-    -e "LOCAL_GROUP_IDS=$LOCAL_GROUP_IDS" \
-    -e "TERRAFORM_OPT=$TERRAFORM_OPT" \
-    -e "ANSIBLE_OPT=$ANSIBLE_OPT" \
-    --env-file <(env | grep OS_) \
-    --env-file <(env | grep TF_) \
-    --env-file <(env | grep GOOGLE_) \
-    --env-file <(env | grep AWS_) \
-    --env-file <(env | grep ARM_) \
-    --env-file <(env | grep KUBENOW_) \
-    kubenow/provisioners:"$KUBENOW_VERSION" \
-    "/KubeNow_root/bin/docker-entrypoint" "$@"
-fi
+esac
+
